# Generated by Django 3.1.7 on 2021-03-31 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0002_auto_20210327_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenderegisteruser',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extenderegisteruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_Registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
