# Generated by Django 3.1.7 on 2021-04-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210331_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenderegisteruser',
            name='trial_days',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
